spring:
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760
  redis:
    host: 121.5.37.158
    port: 6379
    password:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

  # 国际化文件配置
  messages:
    basename: i18n/message

comment.avatar: /images/avatar.png

#      #SQL查询,用来验证从连接池取出的连接
#      dbcp.validationQuery=SELECT 1
#      #指明连接是否被空闲连接回收器(如果有)进行检验，如果检测失败，则连接将被从池中去除
#      dbcp.testWhileIdle=true
#      #在空闲连接回收器线程运行期间休眠的时间值,以毫秒为单位，一般比minEvictableIdleTimeMillis小
#      dbcp.timeBetweenEvictionRunsMillis=300000
#      #在每次空闲连接回收器线程(如果有)运行时检查的连接数量，最好和maxActive一致
#      dbcp.numTestsPerEvictionRun=50
#      #连接池中连接，在时间段内一直空闲，被逐出连接池的时间(1000*60*60)，以毫秒为单位
#      dbcp.minEvictableIdleTimeMillis=3600000