## 生产环境配置文件

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.5.37.158:3306/blog2?useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://121.5.37.158:3306/blog2?serverTimezone=UTC&characterEncoding=utf-8
    username: blog2
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

logging:
  level:
    root: warn
    com.wb: info
  file: log/blog-pro.log
server:
  port: 80